### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by Samuel-Martineau** [Claudiohbsantos/github-material-icons-extension#1]
Do you have any intention to publish this extension to the Firefox addons marketplace?

**Comment by Claudiohbsantos** [comment]
(I think I might have answered you on reddit just now)

I wasn't planning to but mostly because I hadn't even thought about that. I have never looked into developing extensions for firefox so I can't tell for sure but I think it should be a pretty straight forward port. If enough people show interest I'd be more than happy to research that. Also very happy to take Pull Requests for that into this repo if you happen to have experience with that.

**Comment by Samuel-Martineau** [comment]
It wasn't me who asked you about it on Reddit... Also, if I remember correctly, Firefox extensions are the same as Chrome extensions. 

https://extensionworkshop.com/documentation/publish/package-your-extension/

**Comment by Claudiohbsantos** [comment]
Oh, sorry, both messages came in pretty much at the same time so I thought it might be the same request.

Thanks for the link, that looks promising. Their compatibility tested actually reports the extension is compatible already so I'll try running it on firefox later today when I get a chance and if it works I'll try adding it to the firefox extensions

**Comment by Claudiohbsantos** [comment]
Managed to add it to the firefox store: https://addons.mozilla.org/en-US/firefox/addon/material-icons-for-github/

thanks for the pointers!

I ran a quick test on firefox and it looks like it's running without a problem, but please don't hesitate to let me know if you notice any weirdness. Since that's not my main browser I won't use it enough to notice any quirks

**Comment by callmetwan** [comment]
Wow, this was fast, thank you!!

**Comment by Samuel-Martineau** [comment]
Thanks!

**Comment by ehmicky** [comment]
This is great!
Would it be possible to submit it to https://addons.mozilla.org?

**Comment by Claudiohbsantos** [comment]
Yeah, that is on the todo list for today. Just need to see if they have a badge I can use to keep the look similar to what is currently on the readme for the chrome web store.

**Comment by arturoeh** [comment]
The extension is no longer available in the Firefox add-on market.

![Screenshot 2021-07-10 at 20 33 56](https://user-images.githubusercontent.com/40857565/125181891-27a39580-e1be-11eb-92b6-83b53ff39431.png)

**Comment by Claudiohbsantos** [comment]
@arturoeh 🙈 I was racing to try to finish the last changes before updating the add-on. Looks like I lost the race, sorry.

I just submitted an updated version to the store, it is currently awaiting review (last time it took 1 day)

I also just pushed new github actions that should automatically update the store on new upstream versions, so this shouldn't happen again

**Comment by Claudiohbsantos** [comment]
I just finished a new version that should make it simpler for the extension to go through their review process. It's in the queue now, let's see how that goes 🤞 

I'll check/answer any followup in #26 since that issue is still open. Feel free to followup there if it's not live/working in about a week.

Thanks for the reminder :)
