### ISSUE TITLE
Why is the 5 of the html icon not white?

### ISSUE THREAD

**Issue by KrlitosForever** [Claudiohbsantos/github-material-icons-extension#19]
I'd like to know, why isn't it white? in my dark theme it doesn't look good.

**Comment by shivapoudel** [comment]
@KrlitosForever It is because the 5 word in the HTML SVG image is transparent thus it will look like this in the screenshot below and is intentional. See https://github.com/PKief/vscode-material-icon-theme/blob/main/icons/html.svg

![image](https://user-images.githubusercontent.com/3774827/128586706-c6da7910-3820-4109-b301-c63d5c1a9ac8.png)

At least for me, it is good enough and if you think this can be improved then you can approach a ticket for this icon to our dependent [vscode-material-icon-theme](https://github.com/PKief/vscode-material-icon-theme) repo, my friend :)

**Comment by KrlitosForever** [comment]
Dear @shivapoudel , I want to thank the time you have dedicated to the explanation.
I also thank you for the diligence you responded.
I hope you have a good day. A hug.
