### ISSUE TITLE
[icon request] html 

### ISSUE THREAD

**Issue by KrlitosForever** [Claudiohbsantos/github-material-icons-extension#21]
Dear Juan, nice to say hello, I would like to request that the 5 of html be white. Since for clear topics this is not affected. However on dark backgrounds this one looks much better. Comparative image attached.
Hoping for a good reception, I say goodbye.

![html5](https://user-images.githubusercontent.com/7423579/129913801-b0dfd831-e456-492a-ac72-e24cead2c387.png)

**Comment by Claudiohbsantos** [comment]
Hey @KrlitosForever.

This repository doesn't handle individual icon changes because we pull all icons directly from the [VSCode Material Icon Theme](https://github.com/PKief/vscode-material-icon-theme)

Please open an issue on that repository if you'd like to see this changed, and this extension will automatically be updated if the upstream repository is updated 

Thanks!
