### ISSUE TITLE
add support for Nestjs framework

### ISSUE THREAD

**Issue by yan-almeida** [Claudiohbsantos/github-material-icons-extension#22]
![image](https://user-images.githubusercontent.com/56321281/134619647-d4e2a08a-d038-4b9e-ab76-1a238c8b1511.png)

**Comment by Claudiohbsantos** [comment]
The [upstream project](https://github.com/PKief/vscode-material-icon-theme) that provides the icons seems to already include these icons. Can you confirm if the icons appear as expected in VSCode? If they appear in VSCode but not in github using this extension, could you point me towards a repository that I can use to confirm the behavior?

Thanks, just trying to make sure I understand if the issue  should be looked into in this repo or upstream

**Comment by yan-almeida** [comment]
In my public repo: https://github.com/yan-almeida/desafio-eureka-web-api/tree/master/src/decorators 

On vscode: ![image](https://user-images.githubusercontent.com/56321281/135350749-596d2979-b1f0-46c2-a64c-ca9654e1a298.png)

But in my vscode, I use this setting:   **"material-icon-theme.activeIconPack": "nest"**

**Comment by Claudiohbsantos** [comment]
Thanks for these, this is very helpful!

I see. The extension doesn't currently support the the icons that are set explicitly with that setting. It is something that we discussed before but I haven't really had time to look too deeply into. I'll see if I can figure out why the vscode extension decided to make that an IconPack instead of part of the default mappings. If there are no conflicts, I'll try to just include these into the default icons. Otherwise we'll need some way for users to enable/disable iconPacks which is a whole different beast

**Comment by Claudiohbsantos** [comment]
Small, unexciting update on this: Support for the icons themselves have already been merged in the beginning of Nov with [2c0e7d5ad66ad027580366d9718900e0429afe0a](https://github.com/Claudiohbsantos/github-material-icons-extension/commit/2c0e7d5ad66ad027580366d9718900e0429afe0a) . The issue here is that different iconPacks present different icons for the same filename (which is why the vscode extension exposes this as a separate setting). I'm halfway through making a "settings dropdown" for this extension where this icon pack can be selected. See the `settingsInterface` branch for details. Getting this extension on the firefox add-on store has been taking precedence though, which is why this has stalled. If everything works as expected with v1.5.0 released today this will be back to the top of the priority list :)

**Comment by Claudiohbsantos** [comment]
Ok, this is finally complete. I just pushed changes that include a new popup menu and options page that allows users to pick custom icon packs for use, including NestJS. This will be included in the next chrome store release, which should go out sometime this week

![iyGbZ7FDNX](https://user-images.githubusercontent.com/11323215/181416913-7a5263e9-7156-4791-80c9-3a0d65707222.gif)
.
