### ISSUE TITLE
Firefox: Unable to Install: Appears to be corrupt

### ISSUE THREAD

**Issue by l-zeuch** [Claudiohbsantos/github-material-icons-extension#23]
**Firefox version:**
78.14.0esr

**Addon version:**
v1.4.2 (latest release as of now)

**Steps to reproduce:**
Follow the steps provided in the README:
* Download release for Firefox
* Install via `about:addons` -> "install from file"
* see error "appears to be corrupt" (screenshot attached)

![image of error](https://user-images.githubusercontent.com/71897876/134825434-90ad0897-547d-43f8-b6a4-1405bca4103f.png)

**Other Solutions I tried:**
* Cloning the repository and zipping it myself

**Comment by Claudiohbsantos** [comment]
Sorry about that, you are correct that the installatino doesn't work.

The extension is not corrupt, but firefox shows that (very unhelpful) message when attempting to install an unsigned extension. You can temporarily install the extension in debug mode by going to `about:debugging`. That's not very useful though because extensions loaded that way don't persist browser close/re-opens.

There seems to be a couple of ways to disable the signature check for add-on installation but I can't really recommend it since they seem like a lot of work for a bad hack.

I just cut a new release and am submitting it for Firefox approval one more time. According to them it could take a bit for it to be reviewed though

![delays](https://user-images.githubusercontent.com/11323215/135199921-9713e29d-7ade-48a2-8738-f236ef4a6aaf.png)

**Comment by Claudiohbsantos** [comment]
I'm going to close this issue since there is nothing else I can do besides wait for review. Ill see if I can change the way the SVGs are loaded to avoid the need for manual reviews, but that's a bigger change that might not happen immediately. Thanks for the report!

**Comment by l-zeuch** [comment]
Thank you for your answer and the insight.

Really hope Mozilla reviews it ASAP, it's a super cool extension, thank you for your work!
