### ISSUE TITLE
The extension might have been removed from the firefox addons page.

### ISSUE THREAD

**Issue by MrQUACKK** [Claudiohbsantos/github-material-icons-extension#26]
Following the link in the README gets me to a page which basically says the extension no longer exists and it is not included in the search results when searching for it, as far as I can tell it is still on the chrome webstore and the edge addons page.
![2021-10-13-091837_1524x610_scrot](https://user-images.githubusercontent.com/80370416/137140517-f68ca072-44f1-4c22-a0f3-3cdae35e9d88.png)
![2021-10-13-091823_1413x435_scrot](https://user-images.githubusercontent.com/80370416/137140520-965db5b4-ef87-4444-b97c-e9b6de2d27d9.png)

**Comment by Claudiohbsantos** [comment]
Ok, version 1.5.0 was just released and completely get's rid of `innerHTML`. I didn't notice any performance issues on Chrome so I'm crossing my fingers that this will be it. Submitted the new version to Firefox, let's see if this already gets this moving again.

Next step will be to stop using Parcel to bundle the extension just to simplify the project/reviews. This shouldn't be too hard, it's mostly boring since this will involve re-implementing what I'm currently using `selector-observer' for.  Oh well, I'm sure there will be plenty of snow days ahead so this might happen sometime soon :)

**Comment by Claudiohbsantos** [comment]
Version 1.5.1 is live on the addons page 😌 . Closing this issue now. If there are any issues with v1.5.1 running in Firefox please open a new issue so I know it's a compatibility problem and not an addon review problem. Thanks!
