### ISSUE TITLE
Preserve symlink and submodule icons

### ISSUE THREAD

**Issue by kidonng** [Claudiohbsantos/github-material-icons-extension#3]
Symlinked folders/files (including submodules) have a different icon to indicate their type, but this extension doesn't preserve it.

Without extension:
![image](https://user-images.githubusercontent.com/44045911/120326239-19d73680-c31b-11eb-8aee-35108297adfb.png)

With extension:

![image](https://user-images.githubusercontent.com/44045911/120326321-307d8d80-c31b-11eb-8fdb-70686b91815b.png)

Test repo: https://github.com/lxqt/lxqt

**Comment by Claudiohbsantos** [comment]
That's a very good point. The VSCode extension doesn't seem to need any special handling of symlinks because there is another indicator in the explorer for such files/folders, but in this case it becomes undistinguishable.

I'll look into how to painlessly skip modifying these icons without having to change the upstream icon mappings

**Comment by Claudiohbsantos** [comment]
Submodules now show the "git" folder icon, and symlinks have a new custom icon. See image below for reference

![chrome_744kL8oHOo](https://user-images.githubusercontent.com/11323215/126419096-e9b5a8b8-dba3-4ef4-93cf-7cd3759bac52.png)


I'm closing this issue since this change should make it into the next release already. Thanks for opening it :)

**Comment by kidonng** [comment]
Awesome! Thanks for your work.
