### ISSUE TITLE
is it possible to copy the same configuration to vscode?

### ISSUE THREAD

**Issue by douglasgomes98** [Claudiohbsantos/github-material-icons-extension#34]

**Comment by dovatti** [comment]
I think you're bit confused. You can't use [this icon extension](https://github.com/Claudiohbsantos/github-material-icons-extension) in `Visual Studio Code` because it's designed for `GitHub`.
Actually you can use the icon pack this extension uses: you can see check it out [here](https://github.com/PKief/vscode-material-icon-theme).

For installing it just go to `Visual Studio Code Marketplace` in the official [project page](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme). After doing that simply activate it as written in the [repo readme](https://github.com/PKief/vscode-material-icon-theme#one-click-activation).

**Comment by douglasgomes98** [comment]
In fact, I managed to make it very similar, it was only necessary to add some settings in vscode.
`
 "workbench.iconTheme": "material-icon-theme",
 "material-icon-theme.folders.color": "#42a5f5",
 "material-icon-theme.activeIconPack": "react_redux",
`

thanks!
