### ISSUE TITLE
add icon to fql

### ISSUE THREAD

**Issue by J4c5** [Claudiohbsantos/github-material-icons-extension#37]
hello icon material devs, I'm very satisfied with your icon theme, I love it I always use it, today I went to create a scraper with [ferret](https://www.montferret.dev/), using fql a declarative scraper language for ferret, but the file didn't have an icon, add one icone for fql files, if you want an image here is one: [image](https://www.montferret.dev/img/logo.png).

:heart:  Thank you, until next time!

**Comment by J4c5** [comment]
note: I didn't do a PR to add an icon because I don't know how an icon theme works in vscode, so I opened an insue, I hope it's not a problem.

**Comment by dovatti** [comment]
How'd you can see in [about section of readme](https://github.com/Claudiohbsantos/github-material-icons-extension#about) _all icons and file assignments on this project are pulled directly from [VS Code material icon theme](https://github.com/PKief/vscode-material-icon-theme)_, so you might not ask in here for adding an icon... 🙂

My advice is to open an issue in [here](https://github.com/PKief/vscode-material-icon-theme/issues) and ask for it! Easy as that.

**Comment by Claudiohbsantos** [comment]
Hey all! Yeah, unfortunately we don't really handle icon changes/requests on this repo since this only creates the browser extension that in turns uses the icons from the project @dovatti mentioned. Thanks for opening the issue @J4c5, I hope you manage to get it sorted upstream.

I'll close this issue since there is no action to be taken here.
