### ISSUE TITLE
When will the sidebar icon theme extension be supported

### ISSUE THREAD

**Issue by danielesk** [Claudiohbsantos/github-material-icons-extension#44]
![image](https://user-images.githubusercontent.com/10652829/183609614-d9df09a0-c06b-469a-8ae6-f31493ec79bc.png)

**Comment by Claudiohbsantos** [comment]
That screenshot looks like the Octotree sidebar extension, is that correct? If so it looks like that extension already supports using material icons. See if [this link](https://www.octotree.io/features#icon-themes) helps get that started.

**Comment by danielesk** [comment]
@Claudiohbsantos  This feature is only available for paid users, not for free users

![image](https://user-images.githubusercontent.com/10652829/183807223-160896ac-a177-49da-ab1b-5771e5f79b57.png)

**Comment by Claudiohbsantos** [comment]
@danielesk I see. Unfortunately since that sidebar is added by another extension we can't really handle it's icons. Besides that, since that seems to be part of their monetization model I wouldn't be comfortable bypassing it even if we found a way since that's their decision to make. Sorry about that.

I'll close this issue since I don't think there'll be any action taken here, thanks for opening this issue
