### ISSUE TITLE
Doesn't work work on nested routes on Arc Browser

### ISSUE THREAD

**Issue by ChromeGG** [Claudiohbsantos/github-material-icons-extension#53]
Hi, I noticed that this extension doesn't work on nested routes on Arc Browser (which is chromium based)

![CleanShot 2023-02-02 at 20 49 41](https://user-images.githubusercontent.com/39050595/216435354-152c270c-8a9a-494b-b1ab-dd8bae53ea09.png)

I tested it on Brave and everything was fine.

The repo from the screen is [here](https://github.com/ecklf/tailwindcss-radix/tree/main/demo/components)

**Comment by pplmx** [comment]
Chrome has the same issue.

Chrome version: 110.0.5481.178

**Comment by pplmx** [comment]
1. Enter the nested dir
2. Reback the root dir
3. cannot display correctly(It cannot refresh automatically, it works fine on the root dir after the refreshing manually)
4. 
![image](https://user-images.githubusercontent.com/26994103/223303824-43d8b07e-9186-47f8-ba95-e40b58a2f495.png)

**Comment by pplmx** [comment]
Maybe it is also related to #55 and #47

**Comment by Claudiohbsantos** [comment]
Thanks for the tests! The code view related things should be fixed on the next release. I'll close this issue since the first screen shot makes me believe this was actually about the code view (there's a lot of space between those columns for the legacy view). Feel free to reopen if you continue to see issues with Arc
