### ISSUE TITLE
.webmanifest file extension recognized in vscode theme but not in github

### ISSUE THREAD

**Issue by AdamRaichu** [Claudiohbsantos/github-material-icons-extension#54]
In my repo [AdamRaichu/adamraichu.github.io](https://github.com/AdamRaichu/adamraichu.github.io) I have a file `manifest.webmanifest` that I was messing around with. In vscode, it has the JSON file icon, but on GitHub (using the extension) it has the generic file icon.

![image](https://user-images.githubusercontent.com/91494019/219731137-953fce45-ee9a-428a-982f-39a0db895d82.png)

![image](https://user-images.githubusercontent.com/91494019/219731235-93a777f4-6614-4fe4-8025-4d74aa560f7e.png)

**Comment by Claudiohbsantos** [comment]
Thanks for this report! I'll take a look at where the extension is pulling that relationship from. I have a feeling that the open mr related to language mapping might touch this already, but I'll have to check. I'll label this issue in case someone else wants to jump on it first since it'll likely be a little bit before I can focus on it.

**Comment by PKief** [comment]
Yes, the icon association of files ending with ".webmanifest" is based on the language mapping.

**Comment by Claudiohbsantos** [comment]
The issue seems to be resolved with the latest set of updates to language mapping. I expect this to be fixed on the next version that lands in the stores so I'll close this issue. Feel free to reopen if I'm wrong
