### ISSUE TITLE
Improve build / bundling speed with ESBuild

### ISSUE THREAD

**Issue by jamiehaywood** [Claudiohbsantos/github-material-icons-extension#71]
I know the age old saying goes if it ain't broke... but could be good for reducing compute on GH actions, and developing locally.

I propose replacing custom build script and parcel with rollup & esbuild.

Feel free to close if this is not a priority / something you would be interested in.

**Comment by Claudiohbsantos** [comment]
This is definitely a good suggestion and would be good improvements for a project with frequent updates/development. I don't really see much changing in this project on the long term besides fixes and updates to maintain compatibility with github/upstream changes. Because of that I don't really think it's worth the time investment in migrating tools and testing everything.

I'll close this since I don't personally intend to tackle this but feel free to open a PR if you'd like to take a stab at it, we'd just need to test any changes to make sure all builds remain functional.

Thanks for the suggestion though!
